{"name": "Registration login", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62482): Max retries exceeded with url: /session/2645351947ecd3d422c3babd66c20a31/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B76FDB2D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 86, in is_login_no_message\n    home = HomePage(context.driver, True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 11, in __init__\n    self.is_home_available(new_user)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 24, in is_home_available\n    self.wait_element_clickable(*Locator.user_dropdown)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 105, in wait_element_clickable\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 312, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Launch the browser", "status": "passed", "start": 1691072324883, "stop": 1691072325851}, {"name": "When Open the https://courses.ultimateqa.com/users/sign_in website", "status": "passed", "start": 1691072325851, "stop": 1691072327964}, {"name": "Then The login portal has been opened", "status": "passed", "start": 1691072327964, "stop": 1691072327975}, {"name": "When Do not insert any credentials", "status": "passed", "start": 1691072327975, "stop": 1691072328049}, {"name": "Then Click on the Create a new account button", "status": "passed", "start": 1691072328049, "stop": 1691072329291}, {"name": "Then Please insert the information for the new account and Click on Sign up button", "status": "passed", "start": 1691072329291, "stop": 1691072329684}, {"name": "Then Login is successful (no message) and dashboard is opened", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62482): Max retries exceeded with url: /session/2645351947ecd3d422c3babd66c20a31/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B76FDB2D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 86, in is_login_no_message\n    home = HomePage(context.driver, True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 11, in __init__\n    self.is_home_available(new_user)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 24, in is_home_available\n    self.wait_element_clickable(*Locator.user_dropdown)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 105, in wait_element_clickable\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 312, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1691072329684, "stop": 1691072358175}, {"name": "Then Logout the application", "status": "skipped", "start": 1691072358177, "stop": 1691072358177}, {"name": "Then Close the browser", "status": "skipped", "start": 1691072358177, "stop": 1691072358177}], "start": 1691072324882, "stop": 1691072358177, "uuid": "da6a65ca-d871-4f0d-8c2f-822af146f40a", "historyId": "c9a110ff13da5feb2a7ff18950774214", "fullName": "Login scenarios: Registration login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login scenarios"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}